// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nafwsqrjakejgrlgglto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZndzcXJqYWtlamdybGdnbHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDAzMjIsImV4cCI6MjA2NTcxNjMyMn0.fqwG63PHPcJvUCpUZOO_oAo8HRPm5XZ2HotaNAT5zO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);